/**
 * XRPL Testnet Setup Script
 *
 * Creates two wallets (sender/viewer + receiver/creator),
 * funds them with XRP from the testnet faucet,
 * and establishes RLUSD trustlines on both.
 *
 * Run: npx ts-node scripts/xrpl-setup.ts
 */

import * as xrpl from 'xrpl';
import fs from 'fs';
import path from 'path';

const TESTNET_WS = 'wss://testnet.xrpl-labs.com';
const RLUSD_CURRENCY = '524C555344000000000000000000000000000000';
const RLUSD_ISSUER = 'rQhWct2fv4Vc4KRjRgMrxa8xPN9Zx9iLKV';

async function main() {
  console.log('Connecting to XRPL Testnet...');
  const client = new xrpl.Client(TESTNET_WS, { connectionTimeout: 20000 });
  await client.connect();
  console.log('Connected!\n');

  // Step 1: Create and fund two wallets
  console.log('=== Creating Wallet A (sender/viewer) ===');
  const fundResultA = await client.fundWallet();
  const walletA = fundResultA.wallet;
  console.log(`Address: ${walletA.classicAddress}`);
  console.log(`Seed:    ${walletA.seed}`);
  console.log(`XRP:     ${fundResultA.balance} XRP\n`);

  console.log('=== Creating Wallet B (receiver/creator) ===');
  const fundResultB = await client.fundWallet();
  const walletB = fundResultB.wallet;
  console.log(`Address: ${walletB.classicAddress}`);
  console.log(`Seed:    ${walletB.seed}`);
  console.log(`XRP:     ${fundResultB.balance} XRP\n`);

  // Step 2: Set up RLUSD trustline on Wallet A (sender)
  console.log('=== Setting RLUSD trustline on Wallet A ===');
  await setTrustline(client, walletA);

  // Step 3: Set up RLUSD trustline on Wallet B (receiver)
  console.log('=== Setting RLUSD trustline on Wallet B ===');
  await setTrustline(client, walletB);

  // Step 4: Check balances
  console.log('\n=== Final Balances ===');
  const balA = await client.getBalances(walletA.classicAddress);
  const balB = await client.getBalances(walletB.classicAddress);
  console.log('Wallet A:', balA);
  console.log('Wallet B:', balB);

  // Step 5: Save config
  const config = {
    testnet: true,
    wsUrl: TESTNET_WS,
    rlusd: {
      currency: RLUSD_CURRENCY,
      issuer: RLUSD_ISSUER,
    },
    walletA: {
      role: 'sender (viewer)',
      address: walletA.classicAddress,
      seed: walletA.seed,
    },
    walletB: {
      role: 'receiver (creator)',
      address: walletB.classicAddress,
      seed: walletB.seed,
    },
  };

  const envContent = `# XRPL Testnet Configuration (generated by xrpl-setup.ts)
XRPL_TESTNET=true
XRPL_WS_URL=${TESTNET_WS}
XRPL_RLUSD_CURRENCY=${RLUSD_CURRENCY}
XRPL_RLUSD_ISSUER=${RLUSD_ISSUER}
XRPL_SENDER_SEED=${walletA.seed}
XRPL_SENDER_ADDRESS=${walletA.classicAddress}
XRPL_RECEIVER_SEED=${walletB.seed}
XRPL_RECEIVER_ADDRESS=${walletB.classicAddress}
`;

  const configPath = path.resolve(__dirname, '../xrpl-wallets.json');
  const envPath = path.resolve(__dirname, '../../.env');

  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
  fs.writeFileSync(envPath, envContent);

  console.log(`\nSaved wallet config to: ${configPath}`);
  console.log(`Saved .env to: ${envPath}`);

  console.log('\n========================================');
  console.log('SETUP COMPLETE!');
  console.log('========================================');
  console.log('\nTrustlines are set up. Now you need RLUSD tokens.');
  console.log('\nNext steps to get RLUSD:');
  console.log('1. Go to https://tryrlusd.com/');
  console.log('2. Select "XRPL Testnet" tab');
  console.log('3. Click "Connect Wallet"');
  console.log(`4. Claim RLUSD for Wallet A: ${walletA.classicAddress}`);
  console.log(`5. Claim RLUSD for Wallet B: ${walletB.classicAddress}`);
  console.log('\nAlternatively, the backend will work with whatever RLUSD');
  console.log('balance Wallet A has. Even 10 RLUSD is enough for testing.');

  await client.disconnect();
}

async function setTrustline(client: xrpl.Client, wallet: xrpl.Wallet) {
  const trustSetTx: xrpl.TrustSet = {
    TransactionType: 'TrustSet',
    Account: wallet.classicAddress,
    LimitAmount: {
      currency: RLUSD_CURRENCY,
      issuer: RLUSD_ISSUER,
      value: '1000000',
    },
  };

  const prepared = await client.autofill(trustSetTx);
  const signed = wallet.sign(prepared);
  const result = await client.submitAndWait(signed.tx_blob);

  const meta = result.result.meta;
  const txResult = typeof meta === 'object' && meta !== null && 'TransactionResult' in meta
    ? (meta as any).TransactionResult
    : 'unknown';
  console.log(`TrustSet result: ${txResult}`);

  if (txResult !== 'tesSUCCESS') {
    console.error('TrustSet FAILED! Full result:', JSON.stringify(result.result, null, 2));
    throw new Error(`TrustSet failed: ${txResult}`);
  }
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
